"use client";

import { Bell, BrainCircuit, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Circle, ClipboardList, Clock3, GripVertical, LogOut, Pencil, Plus, RefreshCcw, Repeat2, RotateCcw, Settings, Sparkles, Target, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useId, useMemo, useRef, useState } from "react";

type View = "today" | "week" | "month" | "tasks" | "routines" | "goals";
type Block = { id: string; taskId: string | null; title: string; startsAt: string; endsAt: string; status: string; flexibility: string; revision: number; reminderOffsetMinutes: number | null };
type RoutineOccurrence = { id: string; title: string; startsAt: string; endsAt: string; flexibility: string };
type CalendarEvent = { id: string; taskId: string | null; title: string; startsAt: string; endsAt: string; status: string; flexibility: string; revision?: number; reminderOffsetMinutes?: number | null; kind: "task" | "routine" };
type Task = { id: string; goalId: string | null; title: string; description: string | null; estimatedDurationMinutes: number; deadlineAt: string | null; earliestStartAt: string | null; priority: string; flexibility: string; splittable: boolean; minimumChunkMinutes: number | null; status: string; goal: { id: string; title: string } | null; scheduleBlocks: Block[] };
type Routine = { id: string; title: string; recurrence: { daysOfWeek?: number[] }; startMinute: number; endMinute: number; flexibility: string };
type Goal = { id: string; title: string; description: string | null; monthStart: string; status: string; progress: number; tasks: Array<{ id: string; status: string }> };
type Planner = { timezone: string; preferences: { weekStartsOn: number }; tasks: Task[]; routines: Routine[]; blocks: Block[]; routineOccurrences: RoutineOccurrence[]; goals: Goal[] };
type Proposal = { id: string; kind: string; items: Array<{ id: string; title: string; startsAt: string; endsAt: string; durationMinutes: number }>; unscheduled: Array<{ taskId: string; title: string; remainingMinutes: number; reason: string }> };
type Extracted = { title: string; description: string | null; durationMinutes: number; deadlineLocal: string | null; earliestStartLocal: string | null; priority: string; splittable: boolean; minimumChunkMinutes: number | null; confidence: number };
type CurrentUser = { email: string; displayName: string | null; timezone: string; onboardingCompleted: boolean };
type DueReminder = { id: string; scheduleBlock: { title: string; startsAt: string } };
const dayNames = ["Min", "Sen", "Sel", "Rab", "Kam", "Jum", "Sab"];
const emptyTask = { id: "", title: "", description: "", duration: 60, deadline: "", priority: "MEDIUM", flexibility: "FLEXIBLE", splittable: false, minimumChunkMinutes: 30, fixedStart: "", fixedEnd: "", goalId: "" };
const emptyRoutine = { id: "", title: "", days: [1, 2, 3, 4, 5], start: "08:00", end: "09:00" };
const emptyGoal = { id: "", title: "", description: "", month: new Date().toISOString().slice(0, 7), status: "ACTIVE", progress: 0 };
type ScheduleForm = { id: string; title: string; startsAt: string; endsAt: string; revision: number; flexibility: string; reminderOffsetMinutes: number };

async function api<T = unknown>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { cache: "no-store", ...init }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || "Permintaan gagal."); return body as T; }
function keyOf(value: Date | string, timezone: string) { const p = Object.fromEntries(new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(new Date(value)).filter((x) => x.type !== "literal").map((x) => [x.type, x.value])); return `${p.year}-${p.month}-${p.day}`; }
function addDays(key: string, amount: number) { const [y, m, d] = key.split("-").map(Number); return new Date(Date.UTC(y, m - 1, d + amount)).toISOString().slice(0, 10); }
function localToIso(value: string, timezone: string) { if (!value) return null; const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/.exec(value); if (!match) return null; const target = Date.UTC(+match[1], +match[2] - 1, +match[3], +match[4], +match[5]); let guess = target; for (let i = 0; i < 4; i += 1) { const p = Object.fromEntries(new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(guess)).filter((x) => x.type !== "literal").map((x) => [x.type, Number(x.value)])); const diff = target - Date.UTC(p.year, p.month - 1, p.day, p.hour, p.minute); if (!diff) break; guess += diff; } return new Date(guess).toISOString(); }
function instantInput(value: string | null, timezone: string) { if (!value) return ""; const p = Object.fromEntries(new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(value)).filter((x) => x.type !== "literal").map((x) => [x.type, x.value])); return `${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}`; }
function clock(value: string, timezone: string, withDate = false) { return new Intl.DateTimeFormat("id-ID", { timeZone: timezone, ...(withDate ? { weekday: "short", day: "numeric", month: "short" } : {}), hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).format(new Date(value)); }
function minute(value: number) { return `${String(Math.floor(value / 60)).padStart(2, "0")}:${String(value % 60).padStart(2, "0")}`; }
function pushApplicationKey(value: string) { const padding = "=".repeat((4 - value.length % 4) % 4); const decoded = atob((value + padding).replace(/-/g, "+").replace(/_/g, "/")); return Uint8Array.from(decoded, (character) => character.charCodeAt(0)); }
function taskFormValue(task: Task, timezone: string) { return { id: task.id, title: task.title, description: task.description || "", duration: task.estimatedDurationMinutes, deadline: instantInput(task.deadlineAt, timezone).slice(0, 10), priority: task.priority, flexibility: task.flexibility, splittable: task.splittable, minimumChunkMinutes: task.minimumChunkMinutes ?? 30, fixedStart: instantInput(task.scheduleBlocks[0]?.startsAt ?? null, timezone), fixedEnd: instantInput(task.scheduleBlocks[0]?.endsAt ?? null, timezone), goalId: task.goalId || "" }; }

export function PlannerApp() {
  const router = useRouter();
  const [user, setUser] = useState<CurrentUser | null>(null);
  const [planner, setPlanner] = useState<Planner | null>(null); const [view, setView] = useState<View>("today"); const [toast, setToast] = useState(""); const [busy, setBusy] = useState(false);
  const [taskForm, setTaskForm] = useState<typeof emptyTask | null>(null); const [routineForm, setRoutineForm] = useState<typeof emptyRoutine | null>(null); const [goalForm, setGoalForm] = useState<typeof emptyGoal | null>(null);
  const [scheduleForm, setScheduleForm] = useState<ScheduleForm | null>(null); const [weekAnchor, setWeekAnchor] = useState("");
  const [notificationOpen, setNotificationOpen] = useState(false); const [online, setOnline] = useState(true);
  const [draggingBlockId, setDraggingBlockId] = useState<string | null>(null); const [dragOverDay, setDragOverDay] = useState<string | null>(null);
  const [proposal, setProposal] = useState<Proposal | null>(null); const [brainOpen, setBrainOpen] = useState(false); const [brainText, setBrainText] = useState(""); const [brainId, setBrainId] = useState(""); const [extracted, setExtracted] = useState<Extracted[]>([]);
  const timezone = planner?.timezone || user?.timezone || "Asia/Jakarta";
  const query = useMemo(() => { const now = new Date(); return { from: new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1) - 8 * 86400000).toISOString(), to: new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 2, 1)).toISOString() }; }, []);
  const load = useCallback(async () => { const result = await api<{ planner: Planner }>(`/api/planner?from=${encodeURIComponent(query.from)}&to=${encodeURIComponent(query.to)}`); setPlanner(result.planner); localStorage.setItem("assistant-reminder:last-planner", JSON.stringify(result.planner)); }, [query]);
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(""), 3500); }
  useEffect(() => { const timer = window.setTimeout(() => setOnline(navigator.onLine), 0); const connected = () => setOnline(true); const disconnected = () => setOnline(false); window.addEventListener("online", connected); window.addEventListener("offline", disconnected); return () => { window.clearTimeout(timer); window.removeEventListener("online", connected); window.removeEventListener("offline", disconnected); }; }, []);
  useEffect(() => { api<{ user: CurrentUser }>("/api/auth/me").then((result) => { if (!result.user.onboardingCompleted) location.replace("/onboarding"); setUser(result.user); localStorage.setItem("assistant-reminder:last-user", JSON.stringify(result.user)); }).catch(() => { const cached = localStorage.getItem("assistant-reminder:last-user"); if (!navigator.onLine && cached) setUser(JSON.parse(cached)); else location.replace("/login"); }); }, []);
  useEffect(() => { if (!user) return; const timer = window.setTimeout(() => { load().catch((error) => { const cached = localStorage.getItem("assistant-reminder:last-planner"); if (cached) setPlanner(JSON.parse(cached)); else notify(error.message); }); }, 0); return () => window.clearTimeout(timer); }, [user, load]);
  useEffect(() => { if (!user || !online) return; const check = async () => { try { const result = await api<{ jobs: DueReminder[] }>("/api/reminders/due"); for (const job of result.jobs) { if ("Notification" in window && Notification.permission === "granted") { if ("serviceWorker" in navigator) (await navigator.serviceWorker.ready).showNotification(job.scheduleBlock.title, { body: `Mulai ${clock(job.scheduleBlock.startsAt, timezone)}`, icon: "/favicon.svg", tag: `reminder:${job.id}` }); else new Notification(job.scheduleBlock.title, { body: `Mulai ${clock(job.scheduleBlock.startsAt, timezone)}` }); } else notify(`Pengingat: ${job.scheduleBlock.title}`); await api("/api/reminders/due", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: job.id }) }); } } catch {} }; check(); const timer = window.setInterval(check, 60000); return () => window.clearInterval(timer); }, [user, timezone, online]);
  function updatePlanner(updater: (current: Planner) => Planner) { setPlanner((current) => { if (!current) return current; const next = updater(current); localStorage.setItem("assistant-reminder:last-planner", JSON.stringify(next)); return next; }); }
  function applyTask(task: Task) { updatePlanner((current) => ({ ...current, tasks: current.tasks.some((item) => item.id === task.id) ? current.tasks.map((item) => item.id === task.id ? task : item) : [task, ...current.tasks], blocks: [...current.blocks.filter((block) => block.taskId !== task.id), ...task.scheduleBlocks] })); }
  function applyScheduleBlock(block: Block) { updatePlanner((current) => ({ ...current, blocks: current.blocks.map((item) => item.id === block.id ? block : item), tasks: current.tasks.map((task) => task.id === block.taskId ? { ...task, scheduleBlocks: task.scheduleBlocks.map((item) => item.id === block.id ? block : item) } : task) })); }
  async function mutate<T>(action: () => Promise<T>, message: string, apply?: (result: T) => void) { if (!navigator.onLine) return notify("Kamu sedang offline. Jadwal tetap bisa dilihat, tetapi perubahan memerlukan koneksi."); setBusy(true); try { const result = await action(); if (apply) { apply(result); void load().catch(() => undefined); } else await load(); notify(message); } catch (error) { notify(error instanceof Error ? error.message : "Operasi gagal."); } finally { setBusy(false); } }
  const events = useMemo<CalendarEvent[]>(() => planner ? [...planner.blocks.map((x) => ({ ...x, kind: "task" as const })), ...planner.routineOccurrences.map((x) => ({ ...x, taskId: null, status: "PLANNED", kind: "routine" as const }))].sort((a, b) => +new Date(a.startsAt) - +new Date(b.startsAt)) : [], [planner]);
  const today = keyOf(new Date(), timezone); const anchor = weekAnchor || today; const weekday = new Date(`${anchor}T00:00:00Z`).getUTCDay(); const start = addDays(anchor, -((weekday - (planner?.preferences.weekStartsOn ?? 1) + 7) % 7)); const week = Array.from({ length: 7 }, (_, i) => addDays(start, i));
  const todayEvents = events.filter((item) => keyOf(item.startsAt, timezone) === today);
  const completedToday = todayEvents.filter((item) => item.status === "COMPLETED").length;
  const todayProgress = todayEvents.length ? Math.round((completedToday / todayEvents.length) * 100) : 0;
  const unscheduledTasks = planner?.tasks.filter((task) => task.status === "UNSCHEDULED") ?? [];
  const nextEvent = todayEvents.find((item) => item.status !== "COMPLETED" && new Date(item.endsAt) > new Date());
  const displayName = user?.displayName || user?.email.split("@")[0] || "Teman";
  const firstName = displayName.split(" ")[0];
  const initials = displayName.split(" ").slice(0, 2).map((part) => part[0]).join("").toUpperCase();
  const todayLabel = new Intl.DateTimeFormat("id-ID", { weekday: "long", day: "numeric", month: "long", year: "numeric", timeZone: timezone }).format(new Date());
  async function saveTask(event: React.FormEvent) {
    event.preventDefault();
    if (!taskForm) return;
    const isFixed = taskForm.flexibility === "FIXED";
    const fixedStartAt = localToIso(taskForm.fixedStart, timezone);
    const fixedEndAt = localToIso(taskForm.fixedEnd, timezone);
    if (isFixed && (!fixedStartAt || !fixedEndAt || fixedEndAt <= fixedStartAt)) return notify("Waktu selesai harus setelah waktu mulai.");
    const duration = isFixed ? Math.round((new Date(fixedEndAt!).getTime() - new Date(fixedStartAt!).getTime()) / 60000) : Number(taskForm.duration);
    if (duration < 5) return notify("Durasi minimal 5 menit.");
    await mutate(() => api<{ task: Task }>(taskForm.id ? `/api/tasks/${taskForm.id}` : "/api/tasks", {
      method: taskForm.id ? "PUT" : "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({
        title: taskForm.title,
        description: taskForm.description || null,
        estimatedDurationMinutes: duration,
        deadlineAt: !isFixed && taskForm.deadline ? localToIso(`${taskForm.deadline}T23:59`, timezone) : null,
        earliestStartAt: null,
        priority: isFixed ? "MEDIUM" : taskForm.priority,
        flexibility: taskForm.flexibility,
        splittable: !isFixed && taskForm.splittable,
        minimumChunkMinutes: !isFixed && taskForm.splittable ? Number(taskForm.minimumChunkMinutes) : null,
        fixedStartAt,
        goalId: taskForm.goalId || null,
      }),
    }), isFixed ? "Kegiatan tersimpan." : "Tugas fokus tersimpan.", (result) => { applyTask(result.task); setTaskForm(null); });
  }
  async function saveRoutine(event: React.FormEvent) { event.preventDefault(); if (!routineForm) return; const [sh, sm] = routineForm.start.split(":").map(Number); const [eh, em] = routineForm.end.split(":").map(Number); await mutate(async () => { await api(routineForm.id ? `/api/routines/${routineForm.id}` : "/api/routines", { method: routineForm.id ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: routineForm.title, timezone, daysOfWeek: routineForm.days, startMinute: sh * 60 + sm, endMinute: eh * 60 + em, flexibility: "FIXED" }) }); setRoutineForm(null); }, "Rutinitas tersimpan."); }
  async function saveGoal(event: React.FormEvent) { event.preventDefault(); if (!goalForm) return; await mutate(async () => { await api(goalForm.id ? `/api/goals/${goalForm.id}` : "/api/goals", { method: goalForm.id ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: goalForm.title, description: goalForm.description || null, monthStart: `${goalForm.month}-01`, targetAt: null, status: goalForm.status, progress: Number(goalForm.progress) }) }); setGoalForm(null); }, "Target tersimpan."); }
  function openSchedule(block: CalendarEvent) { if (block.kind !== "task" || !block.revision) return; setScheduleForm({ id: block.id, title: block.title, startsAt: instantInput(block.startsAt, timezone), endsAt: instantInput(block.endsAt, timezone), revision: block.revision, flexibility: block.flexibility, reminderOffsetMinutes: block.reminderOffsetMinutes ?? 0 }); }
  async function updateSchedule(block: Pick<ScheduleForm, "id" | "revision"> & { reminderOffsetMinutes?: number | null }, startsAt: string, endsAt: string, close = false) { await mutate(() => api<{ block: Block }>(`/api/schedule-blocks/${block.id}`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ startsAt, endsAt, revision: block.revision, reminderOffsetMinutes: block.reminderOffsetMinutes ?? 0 }) }), "Jadwal dan pengingat diperbarui.", (result) => { applyScheduleBlock(result.block); if (close) setScheduleForm(null); }); }
  async function saveSchedule(event: React.FormEvent) { event.preventDefault(); if (!scheduleForm) return; const startsAt = localToIso(scheduleForm.startsAt, timezone); const endsAt = localToIso(scheduleForm.endsAt, timezone); if (!startsAt || !endsAt) return notify("Tanggal dan jam jadwal belum valid."); await updateSchedule(scheduleForm, startsAt, endsAt, true); }
  async function dropOnDay(event: React.DragEvent, dateKey: string) { event.preventDefault(); const id = event.dataTransfer.getData("text/assistant-reminder-block"); setDraggingBlockId(null); setDragOverDay(null); const block = planner?.blocks.find((item) => item.id === id); if (!block || keyOf(block.startsAt, timezone) === dateKey) return; const localStart = instantInput(block.startsAt, timezone); const startsAt = localToIso(`${dateKey}T${localStart.slice(11)}`, timezone); if (!startsAt) return notify("Tanggal tujuan tidak valid."); const endsAt = new Date(new Date(startsAt).getTime() + new Date(block.endsAt).getTime() - new Date(block.startsAt).getTime()).toISOString(); await updateSchedule(block, startsAt, endsAt); }
  async function enableNotifications() { if (!("Notification" in window) || !("serviceWorker" in navigator)) return notify("Browser ini belum mendukung notifikasi web."); setBusy(true); try { const permission = await Notification.requestPermission(); if (permission !== "granted") { notify("Izin notifikasi tidak diberikan. Fitur lain tetap dapat digunakan."); setNotificationOpen(false); return; } const registration = await navigator.serviceWorker.register("/sw.js"); const config = await api<{ publicKey: string | null }>("/api/notifications/subscription"); if (config.publicKey && "PushManager" in window) { let subscription = await registration.pushManager.getSubscription(); subscription ??= await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: pushApplicationKey(config.publicKey) }); await api("/api/notifications/subscription", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(subscription.toJSON()) }); notify("Notifikasi perangkat berhasil diaktifkan."); } else notify("Izin aktif. Reminder berjalan saat aplikasi terbuka; Web Push latar belakang menunggu konfigurasi server."); setNotificationOpen(false); } catch (error) { notify(error instanceof Error ? error.message : "Notifikasi belum dapat diaktifkan."); } finally { setBusy(false); } }
  async function schedule(reschedule = false) { if (!navigator.onLine) return notify("Penyusunan jadwal memerlukan koneksi."); setBusy(true); try { const result = await api<{ proposal: Proposal }>(reschedule ? "/api/schedule/reschedule" : "/api/schedule/propose", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ rangeStart: localToIso(`${week[0]}T00:00`, timezone), rangeEnd: localToIso(`${addDays(week[6], 1)}T00:00`, timezone) }) }); setProposal(result.proposal); } catch (error) { notify(error instanceof Error ? error.message : "Proposal gagal."); } finally { setBusy(false); } }
  async function brainDump() { if (!navigator.onLine) return notify("Brain Dump memerlukan koneksi ke server lokal."); setBusy(true); try { const result = await api<{ brainDumpId: string; tasks: Extracted[]; warning?: string; summary: string }>("/api/brain-dump", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ rawText: brainText }) }); setBrainId(result.brainDumpId); setExtracted(result.tasks); notify(result.warning || result.summary); } catch (error) { notify(error instanceof Error ? error.message : "Brain Dump gagal."); } finally { setBusy(false); } }
  if (!user || !planner) return <main className="planner-loading"><Sparkles /> Menyiapkan perencanamu…</main>;
  const nav: Array<[View, string, typeof Clock3]> = [["today", "Hari ini", Clock3], ["week", "Minggu", CalendarDays], ["month", "Bulan", Target], ["tasks", "Tugas", ClipboardList], ["routines", "Rutinitas", Repeat2], ["goals", "Target", Target]];
  return <main className="planner-shell">
    <aside className="planner-sidebar">
      <div className="planner-brand"><span><Sparkles /></span><div><strong>Assistant</strong><small>Reminder</small></div></div>
      <button className="brain-action" onClick={() => setBrainOpen(true)}><BrainCircuit /> Brain Dump <kbd>⌘ B</kbd></button>
      <nav><small>Perencana</small>{nav.map(([id, label, Icon]) => <button key={id} className={view === id ? "active" : ""} onClick={() => setView(id)}><Icon />{label}{id === "tasks" && planner.tasks.length > 0 && <em>{planner.tasks.length}</em>}</button>)}</nav>
      <div className="sidebar-bottom">
        <button onClick={() => setNotificationOpen(true)}><Bell />Pengingat</button>
        <button onClick={() => router.push("/settings")}><Settings />Pengaturan</button>
        <div className="planner-profile"><span>{initials}</span><div><strong>{displayName}</strong><small>{timezone}</small></div><button aria-label="Keluar" onClick={async () => { await fetch("/api/auth/logout", { method: "POST" }); localStorage.removeItem("assistant-reminder:last-planner"); localStorage.removeItem("assistant-reminder:last-user"); navigator.serviceWorker?.controller?.postMessage("CLEAR_PRIVATE_CACHE"); location.replace("/login"); }}><LogOut /></button></div>
      </div>
    </aside>
    <section className="planner-main">
      <div className="planner-topbar"><span><CalendarDays />{todayLabel}</span><div><button className="notification-button" aria-label="Atur notifikasi" onClick={() => setNotificationOpen(true)}><Bell /></button><button className="primary" disabled={!online} onClick={() => setTaskForm({ ...emptyTask })}><Plus />Tambah rencana</button></div></div>
      {!online && <div className="offline-banner" role="status"><span>Mode offline</span> Jadwal terakhir tetap dapat dilihat. Perubahan akan aktif kembali setelah tersambung.</div>}
      <header className="planner-header"><div><small>{view === "today" ? "Agenda hari ini" : "Perencana personal"}</small><h1>{view === "today" ? `Selamat datang, ${firstName}.` : nav.find(([id]) => id === view)?.[1]}</h1><p>{view === "today" ? (todayEvents.length ? `${todayEvents.length} kegiatan tersusun untuk hari ini. Jaga ritmemu tetap ringan dan realistis.` : "Belum ada agenda untuk hari ini. Mulai dari satu tugas kecil atau susun minggu otomatis.") : "Kelola rencana dengan tampilan yang ringkas dan mudah dipahami."}</p></div><div><button disabled={busy || !online} onClick={() => schedule(true)}><RefreshCcw />Susun ulang</button><button disabled={!online} onClick={() => mutate(() => api("/api/schedule/undo", { method: "POST" }), "Jadwal dipulihkan.")}><RotateCcw />Undo</button><button className="primary" disabled={!online} onClick={() => setTaskForm({ ...emptyTask })}><Plus />Rencana</button></div></header>
      {view === "today" && <>
        <div className="planner-summary-grid">
          <article className="planner-summary-card"><div className="planner-progress-ring" style={{ "--progress": `${todayProgress}%` } as React.CSSProperties}><span>{todayProgress}%</span></div><div><small>Progres hari ini</small><strong>{completedToday} dari {todayEvents.length} selesai</strong><p>{todayEvents.length ? "Ritmemu masih sesuai rencana" : "Belum ada kegiatan"}</p></div></article>
          <article className="planner-summary-card"><div className="planner-summary-icon"><Target /></div><div><small>Fokus berikutnya</small><strong>{nextEvent?.title || "Belum ditentukan"}</strong><p>{nextEvent ? `Mulai pukul ${clock(nextEvent.startsAt, timezone)}` : "Tambahkan tugas untuk memulai"}</p></div></article>
          <article className="planner-summary-card"><div className="planner-summary-icon amber"><ClipboardList /></div><div><small>Belum dijadwalkan</small><strong>{unscheduledTasks.length} tugas</strong><p>{unscheduledTasks.length ? "Siap dimasukkan ke jadwal" : "Semua tugas sudah tertata"}</p></div></article>
        </div>
        <div className="planner-columns">
          <Panel title="Agenda hari ini" action={<button onClick={() => schedule()}><RefreshCcw />Susun minggu</button>}>
            {todayEvents.length ? todayEvents.map((x) => <article className={`planner-event ${x.status === "COMPLETED" ? "done" : ""}`} key={x.id}><time>{clock(x.startsAt, timezone)}<span>{clock(x.endsAt, timezone)}</span></time><div><strong>{x.title}</strong><small>{x.kind === "routine" ? "Rutinitas berulang" : x.flexibility === "FIXED" ? "Kegiatan terjadwal" : "Sesi tugas fokus"}</small></div>{x.kind === "task" && x.status !== "COMPLETED" && <button className="planner-event-edit" aria-label={`Ubah jadwal ${x.title}`} onClick={() => openSchedule(x)}><Pencil /></button>}{x.taskId && <button aria-label={`Selesaikan ${x.title}`} onClick={() => mutate(() => api(`/api/tasks/${x.taskId}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: "COMPLETED" }) }), "Tugas selesai.")}>{x.status === "COMPLETED" ? <CheckCircle2 /> : <Circle />}</button>}</article>) : <EmptyState icon={<Clock3 />} title="Agenda hari ini masih kosong" description="Tambahkan kegiatan yang waktunya pasti atau tugas fokus untuk disusun otomatis." action={<button className="primary" onClick={() => setTaskForm({ ...emptyTask })}><Plus />Buat rencana pertama</button>} />}
          </Panel>
          <Panel title="Belum dijadwalkan">
            {unscheduledTasks.length ? unscheduledTasks.map((x) => <button className="compact-task" key={x.id} onClick={() => setTaskForm(taskFormValue(x, timezone))}><span className={`priority-dot ${x.priority.toLowerCase()}`} /><span><strong>{x.title}</strong><small>{x.estimatedDurationMinutes} menit · {x.priority}</small></span></button>) : <EmptyState compact icon={<CheckCircle2 />} title="Semua sudah tertata" description="Tidak ada tugas yang menunggu jadwal." />}
          </Panel>
        </div>
      </>}
      {view === "week" && <Panel title="Kalender mingguan" action={<div className="week-actions"><button aria-label="Minggu sebelumnya" onClick={() => setWeekAnchor(addDays(week[0], -7))}><ChevronLeft /></button><button onClick={() => setWeekAnchor(today)}>Hari ini</button><button aria-label="Minggu berikutnya" onClick={() => setWeekAnchor(addDays(week[0], 7))}><ChevronRight /></button><button className="primary" onClick={() => schedule()}><Sparkles />Buat proposal</button></div>}><p className="week-help">Desktop: seret kartu ke hari lain untuk mempertahankan jamnya. Ketuk kartu untuk mengubah tanggal, jam mulai, atau jam selesai secara tepat. Pada handphone gunakan ketuk agar layar tetap mudah digulir.</p><div className="week-board">{week.map((key) => { const dayEvents = events.filter((item) => keyOf(item.startsAt, timezone) === key); return <div className={`${key === today ? "today" : ""} ${dragOverDay === key ? "drag-over" : ""}`} key={key} onDragEnter={(event) => { event.preventDefault(); setDragOverDay(key); }} onDragOver={(event) => { event.preventDefault(); event.dataTransfer.dropEffect = "move"; }} onDragLeave={(event) => { if (!event.currentTarget.contains(event.relatedTarget as Node | null)) setDragOverDay(null); }} onDrop={(event) => dropOnDay(event, key)}><h3>{dayNames[new Date(`${key}T00:00:00Z`).getUTCDay()]} <span>{key.slice(-2)}</span></h3>{dayEvents.length ? dayEvents.map((item) => item.kind === "task" ? <button className={`week-event ${draggingBlockId === item.id ? "dragging" : ""}`} draggable onDragStart={(event) => { setDraggingBlockId(item.id); event.dataTransfer.effectAllowed = "move"; event.dataTransfer.setData("text/assistant-reminder-block", item.id); }} onDragEnd={() => { setDraggingBlockId(null); setDragOverDay(null); }} onClick={() => openSchedule(item)} key={item.id}><small>{clock(item.startsAt, timezone)}–{clock(item.endsAt, timezone)}</small><strong>{item.title}</strong><span className="drag-hint"><GripVertical />Seret ke hari lain · ketuk untuk atur jam</span></button> : <p className="week-event routine" key={item.id}><small>{clock(item.startsAt, timezone)}–{clock(item.endsAt, timezone)}</small><strong>{item.title}</strong><span>Rutinitas berulang</span></p>) : <em>{draggingBlockId ? "Lepaskan di sini" : "Belum ada jadwal"}</em>}</div>; })}</div></Panel>}
      {view === "month" && <Panel title="Ringkasan bulan">{planner.goals.length ? <Cards>{planner.goals.map((g) => <article key={g.id}><div><strong>{g.title}</strong><small>{g.tasks.length} tugas terhubung</small></div><Progress value={g.progress} /><small>{g.progress}% tercapai</small></article>)}</Cards> : <EmptyState icon={<Target />} title="Belum ada target bulan ini" description="Buat satu target agar tugas harianmu punya arah yang jelas." action={<button className="primary" onClick={() => setGoalForm({ ...emptyGoal })}><Plus />Buat target</button>} />}</Panel>}
      {view === "tasks" && <Panel title="Daftar rencana" action={<button className="primary" onClick={() => setTaskForm({ ...emptyTask })}><Plus />Rencana</button>}>{planner.tasks.length ? <div className="planner-list">{planner.tasks.map((t) => <article key={t.id} className={t.status === "COMPLETED" ? "done" : ""}><button onClick={() => mutate(() => api(`/api/tasks/${t.id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status: "COMPLETED" }) }), "Tugas selesai.")}>{t.status === "COMPLETED" ? <CheckCircle2 /> : <Circle />}</button><button className="item-copy" onClick={() => setTaskForm(taskFormValue(t, timezone))}><strong>{t.title}</strong><small>{t.flexibility === "FIXED" ? `Kegiatan terjadwal · ${t.scheduleBlocks[0] ? clock(t.scheduleBlocks[0].startsAt, timezone, true) : "waktu belum tersedia"}` : `Tugas fokus · ${t.estimatedDurationMinutes} menit · ${t.priority}`}</small></button><button aria-label={`Hapus ${t.title}`} onClick={() => mutate(() => api(`/api/tasks/${t.id}`, { method: "DELETE" }), "Tugas dihapus.")}><Trash2 /></button></article>)}</div> : <EmptyState icon={<ClipboardList />} title="Daftar rencana masih kosong" description="Tambahkan tugas fokus yang perlu dicarikan waktu atau kegiatan yang jamnya sudah pasti." action={<button className="primary" onClick={() => setTaskForm({ ...emptyTask })}><Plus />Tambah rencana</button>} />}</Panel>}
      {view === "routines" && <Panel title="Rutinitas mingguan" action={<button className="primary" onClick={() => setRoutineForm({ ...emptyRoutine })}><Plus />Rutinitas</button>}>{planner.routines.length ? <Cards>{planner.routines.map((r) => <article key={r.id}><button className="item-copy" onClick={() => setRoutineForm({ id: r.id, title: r.title, days: r.recurrence.daysOfWeek ?? [], start: minute(r.startMinute), end: minute(r.endMinute) })}><strong>{r.title}</strong><small>{(r.recurrence.daysOfWeek ?? []).map((d) => dayNames[d]).join(", ")} · {minute(r.startMinute)}–{minute(r.endMinute)}</small></button><button aria-label={`Hapus ${r.title}`} onClick={() => mutate(() => api(`/api/routines/${r.id}`, { method: "DELETE" }), "Rutinitas dinonaktifkan.")}><Trash2 /></button></article>)}</Cards> : <EmptyState icon={<Repeat2 />} title="Belum ada rutinitas" description="Masukkan kegiatan tetap seperti kerja, kuliah, olahraga, atau waktu istirahat." action={<button className="primary" onClick={() => setRoutineForm({ ...emptyRoutine })}><Plus />Tambah rutinitas</button>} />}</Panel>}
      {view === "goals" && <Panel title="Target bulanan" action={<button className="primary" onClick={() => setGoalForm({ ...emptyGoal })}><Plus />Target</button>}>{planner.goals.length ? <Cards>{planner.goals.map((g) => <article key={g.id}><button className="item-copy" onClick={() => setGoalForm({ id: g.id, title: g.title, description: g.description || "", month: g.monthStart.slice(0, 7), status: g.status, progress: g.progress })}><strong>{g.title}</strong><Progress value={g.progress} /><small>{g.progress}% · {g.status}</small></button><button aria-label={`Hapus ${g.title}`} onClick={() => mutate(() => api(`/api/goals/${g.id}`, { method: "DELETE" }), "Target dihapus.")}><Trash2 /></button></article>)}</Cards> : <EmptyState icon={<Target />} title="Target bulanan masih kosong" description="Tentukan hasil yang ingin kamu capai bulan ini, lalu hubungkan tugas-tugasmu ke target tersebut." action={<button className="primary" onClick={() => setGoalForm({ ...emptyGoal })}><Plus />Buat target pertama</button>} />}</Panel>}
    </section>
    {notificationOpen && <Modal title="Notifikasi pengingat" close={() => setNotificationOpen(false)}><div className="notification-setup"><span className="notification-setup-icon"><Bell /></span><h3>Ingat jadwal tanpa terus membuka aplikasi</h3><p>Assistant Reminder akan meminta izin browser dan mengingatkan sebelum kegiatan dimulai. Kamu tetap dapat memakai semua fitur jika memilih tidak mengizinkan.</p><ul><li>Reminder default dibuat 15 menit sebelum jadwal.</li><li>Jam reminder ikut diperbarui ketika jadwal dipindahkan.</li><li>Pengiriman latar belakang bersifat best effort dan memerlukan server HTTPS yang aktif.</li></ul><div className="form-actions"><button onClick={() => setNotificationOpen(false)}>Nanti saja</button><button className="primary" disabled={busy || !online} onClick={enableNotifications}>Aktifkan notifikasi</button></div></div></Modal>}
    {scheduleForm && <Modal title="Ubah jadwal" close={() => setScheduleForm(null)}><form className="planner-form schedule-form" onSubmit={saveSchedule}><div className="schedule-form-intro"><span><Clock3 /></span><div><strong>{scheduleForm.title}</strong><small>{scheduleForm.flexibility === "FIXED" ? "Kegiatan terjadwal" : "Sesi tugas fokus"}</small></div></div><div className="form-pair"><label>Mulai<input required step="900" type="datetime-local" value={scheduleForm.startsAt} onChange={(event) => setScheduleForm({ ...scheduleForm, startsAt: event.target.value })} /></label><label>Selesai<input required step="900" type="datetime-local" value={scheduleForm.endsAt} onChange={(event) => setScheduleForm({ ...scheduleForm, endsAt: event.target.value })} /></label></div><label>Ingatkan<select value={scheduleForm.reminderOffsetMinutes} onChange={(event) => setScheduleForm({ ...scheduleForm, reminderOffsetMinutes: Number(event.target.value) })}><option value="0">Tanpa pengingat</option><option value="5">5 menit sebelumnya</option><option value="15">15 menit sebelumnya</option><option value="30">30 menit sebelumnya</option><option value="60">1 jam sebelumnya</option><option value="1440">1 hari sebelumnya</option></select></label><p className="schedule-form-help">Perubahan menggunakan interval 15 menit. Sistem akan menolak jam tidur, deadline tugas terlewati, dan jadwal yang bertabrakan.</p><div className="form-actions"><button type="button" onClick={() => setScheduleForm(null)}>Batal</button><button className="primary" disabled={busy}>{busy ? "Menyimpan…" : "Simpan jadwal"}</button></div></form></Modal>}
    {taskForm && <Modal title={taskForm.id ? "Ubah rencana" : "Rencana baru"} close={() => setTaskForm(null)}><form className="planner-form" aria-busy={busy} onSubmit={saveTask}>
      <div className="plan-kind-picker" role="group" aria-label="Jenis rencana">
        <button type="button" className={taskForm.flexibility === "FLEXIBLE" ? "active" : ""} aria-pressed={taskForm.flexibility === "FLEXIBLE"} onClick={() => setTaskForm({ ...taskForm, flexibility: "FLEXIBLE" })}><Target /><span><strong>Tugas fokus</strong><small>Jamnya dicarikan oleh assistant</small></span></button>
        <button type="button" className={taskForm.flexibility === "FIXED" ? "active" : ""} aria-pressed={taskForm.flexibility === "FIXED"} onClick={() => setTaskForm({ ...taskForm, flexibility: "FIXED", splittable: false })}><CalendarDays /><span><strong>Kegiatan berjadwal</strong><small>Tanggal dan jamnya sudah pasti</small></span></button>
      </div>
      <label>Judul<input required value={taskForm.title} onChange={(event) => setTaskForm({ ...taskForm, title: event.target.value })} /></label>
      <label>Catatan <span className="optional">opsional</span><textarea value={taskForm.description} onChange={(event) => setTaskForm({ ...taskForm, description: event.target.value })} /></label>
      {taskForm.flexibility === "FLEXIBLE" ? <>
        <div className="form-pair"><label>Butuh waktu berapa lama?<input required type="number" min="5" max="1440" step="5" value={taskForm.duration} onChange={(event) => setTaskForm({ ...taskForm, duration: Number(event.target.value) })} /><small className="field-help">Estimasi menit yang dipakai scheduler untuk mencari ruang kosong.</small></label><label>Prioritas<select value={taskForm.priority} onChange={(event) => setTaskForm({ ...taskForm, priority: event.target.value })}><option value="LOW">Rendah</option><option value="MEDIUM">Sedang</option><option value="HIGH">Tinggi</option><option value="URGENT">Mendesak</option></select></label></div>
        <label>Deadline <span className="optional">opsional</span><input type="date" value={taskForm.deadline} onChange={(event) => setTaskForm({ ...taskForm, deadline: event.target.value })} /><small className="field-help">Batas hari penyelesaian, bukan waktu mulai tugas.</small></label>
        <label className="check"><input type="checkbox" checked={taskForm.splittable} onChange={(event) => setTaskForm({ ...taskForm, splittable: event.target.checked })} /><span><strong>Boleh dibagi menjadi beberapa sesi</strong><small>Contoh: belajar 120 menit dapat dibuat menjadi dua sesi 60 menit.</small></span></label>
        {taskForm.splittable && <label>Durasi minimum setiap sesi<input required type="number" min="5" max="240" step="5" value={taskForm.minimumChunkMinutes} onChange={(event) => setTaskForm({ ...taskForm, minimumChunkMinutes: Number(event.target.value) })} /><small className="field-help">Assistant tidak akan membuat sesi lebih pendek dari nilai ini.</small></label>}
      </> : <>
        <div className="form-pair"><label>Mulai<input required step="900" type="datetime-local" value={taskForm.fixedStart} onChange={(event) => setTaskForm({ ...taskForm, fixedStart: event.target.value })} /></label><label>Selesai<input required step="900" type="datetime-local" value={taskForm.fixedEnd} onChange={(event) => setTaskForm({ ...taskForm, fixedEnd: event.target.value })} /></label></div>
        <p className="field-note"><Clock3 />Kegiatan langsung masuk kalender dan tidak dipindahkan ketika jadwal disusun otomatis.</p>
      </>}
      <label>Target <span className="optional">opsional</span><select value={taskForm.goalId} onChange={(event) => setTaskForm({ ...taskForm, goalId: event.target.value })}><option value="">Tanpa target</option>{planner.goals.map((goal) => <option key={goal.id} value={goal.id}>{goal.title}</option>)}</select></label>
      <button className="primary" disabled={busy}>{busy ? "Menyimpan…" : taskForm.flexibility === "FIXED" ? "Simpan kegiatan" : "Simpan tugas fokus"}</button>
    </form></Modal>}
    {routineForm && <Modal title="Rutinitas" close={() => setRoutineForm(null)}><form className="planner-form" onSubmit={saveRoutine}><label>Judul<input required value={routineForm.title} onChange={(e) => setRoutineForm({ ...routineForm, title: e.target.value })} /></label><div className="day-buttons">{dayNames.map((d, i) => <button type="button" className={routineForm.days.includes(i) ? "active" : ""} key={d} onClick={() => setRoutineForm({ ...routineForm, days: routineForm.days.includes(i) ? routineForm.days.filter((x) => x !== i) : [...routineForm.days, i] })}>{d}</button>)}</div><div className="form-pair"><label>Mulai<input type="time" value={routineForm.start} onChange={(e) => setRoutineForm({ ...routineForm, start: e.target.value })} /></label><label>Selesai<input type="time" value={routineForm.end} onChange={(e) => setRoutineForm({ ...routineForm, end: e.target.value })} /></label></div><button className="primary">Simpan</button></form></Modal>}
    {goalForm && <Modal title="Target bulanan" close={() => setGoalForm(null)}><form className="planner-form" onSubmit={saveGoal}><label>Judul<input required value={goalForm.title} onChange={(e) => setGoalForm({ ...goalForm, title: e.target.value })} /></label><label>Deskripsi<textarea value={goalForm.description} onChange={(e) => setGoalForm({ ...goalForm, description: e.target.value })} /></label><div className="form-pair"><label>Bulan<input type="month" value={goalForm.month} onChange={(e) => setGoalForm({ ...goalForm, month: e.target.value })} /></label><label>Progres {goalForm.progress}%<input type="range" min="0" max="100" value={goalForm.progress} onChange={(e) => setGoalForm({ ...goalForm, progress: +e.target.value })} /></label></div><button className="primary">Simpan</button></form></Modal>}
    {brainOpen && <Modal title="Brain Dump" close={() => { setBrainOpen(false); setExtracted([]); }}><div className="planner-form">{!extracted.length ? <><label>Rencana<textarea rows={7} value={brainText} onChange={(e) => setBrainText(e.target.value)} placeholder="Laporan 2 jam sebelum Jumat pukul 17.00" /></label><button className="primary" onClick={brainDump}>Uraikan</button></> : <><div className="extract-list">{extracted.map((x, i) => <article key={i}><input value={x.title} onChange={(e) => setExtracted(extracted.map((a, j) => j === i ? { ...a, title: e.target.value } : a))} /><span>{x.durationMinutes} menit · {x.priority} · {Math.round(x.confidence * 100)}%</span></article>)}</div><button className="primary" onClick={() => mutate(async () => { await api("/api/brain-dump/confirm", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ brainDumpId: brainId, tasks: extracted }) }); setBrainOpen(false); setExtracted([]); setBrainText(""); }, "Tugas Brain Dump tersimpan.")}>Simpan sebagai tugas</button></>}</div></Modal>}
    {proposal && <Modal title="Preview proposal" close={() => setProposal(null)}><div className="proposal-list">{proposal.items.map((x) => <p key={x.id}><strong>{x.title}</strong><span>{clock(x.startsAt, timezone, true)}–{clock(x.endsAt, timezone)}</span></p>)}{proposal.unscheduled.map((x) => <p className="warning" key={x.taskId}>{x.title}: {x.remainingMinutes} menit belum tertampung ({x.reason})</p>)}<button className="primary" disabled={!proposal.items.length} onClick={() => mutate(async () => { await api("/api/schedule/confirm", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ proposalId: proposal.id }) }); setProposal(null); }, "Jadwal diaktifkan.")}>Konfirmasi jadwal</button></div></Modal>}
    {toast && <div className="planner-toast" role="status" aria-live="polite"><CheckCircle2 />{toast}</div>}
  </main>;
}

function Panel({ title, action, children }: { title: string; action?: React.ReactNode; children: React.ReactNode }) { return <section className="planner-panel"><header><h2>{title}</h2>{action}</header>{children}</section>; }
function Cards({ children }: { children: React.ReactNode }) { return <div className="planner-cards">{children}</div>; }
function Progress({ value }: { value: number }) { return <div className="planner-progress"><span style={{ width: `${value}%` }} /></div>; }
function EmptyState({ icon, title, description, action, compact = false }: { icon: React.ReactNode; title: string; description: string; action?: React.ReactNode; compact?: boolean }) { return <div className={`planner-empty ${compact ? "compact" : ""}`}><span>{icon}</span><strong>{title}</strong><p>{description}</p>{action}</div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) {
  const titleId = useId();
  const dialogRef = useRef<HTMLElement>(null);

  useEffect(() => {
    const previouslyFocused = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const frame = window.requestAnimationFrame(() => {
      dialogRef.current?.querySelector<HTMLElement>("button, input, select, textarea, [tabindex]:not([tabindex='-1'])")?.focus();
    });

    return () => {
      window.cancelAnimationFrame(frame);
      previouslyFocused?.focus();
    };
  }, []);

  function handleKeyDown(event: React.KeyboardEvent<HTMLElement>) {
    if (event.key === "Escape") {
      event.preventDefault();
      close();
      return;
    }
    if (event.key !== "Tab") return;

    const focusable = Array.from(
      event.currentTarget.querySelectorAll<HTMLElement>(
        "button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [href], [tabindex]:not([tabindex='-1'])",
      ),
    );
    if (!focusable.length) return;
    const first = focusable[0];
    const last = focusable[focusable.length - 1];
    if (event.shiftKey && document.activeElement === first) {
      event.preventDefault();
      last.focus();
    } else if (!event.shiftKey && document.activeElement === last) {
      event.preventDefault();
      first.focus();
    }
  }

  return <div className="planner-modal-backdrop"><section ref={dialogRef} className="planner-modal" role="dialog" aria-modal="true" aria-labelledby={titleId} onKeyDown={handleKeyDown}><header><h2 id={titleId}>{title}</h2><button type="button" aria-label={`Tutup dialog ${title}`} onClick={close}><X /></button></header>{children}</section></div>;
}
