import { extractionSchema, type extractedTaskSchema } from "@/lib/planner/validation";
import type { z } from "zod";
export type ExtractedTask = z.infer<typeof extractedTaskSchema>;
type Result = { summary: string; tasks: ExtractedTask[] };
const weekdays: Record<string, number> = { minggu: 0, senin: 1, selasa: 2, rabu: 3, kamis: 4, jumat: 5, sabtu: 6 };
function dateKey(date: Date) { return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}-${String(date.getUTCDate()).padStart(2, "0")}`; }
function localBase(now: Date, timezone: string) { const values = Object.fromEntries(new Intl.DateTimeFormat("en-CA", { timeZone: timezone, year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(now).filter((p) => p.type !== "literal").map((p) => [p.type, Number(p.value)])); return new Date(Date.UTC(values.year, values.month - 1, values.day)); }
function deadline(line: string, timezone: string) { const lowered = line.toLowerCase(); const time = /(?:pukul|jam)\s*(\d{1,2})(?:[.:](\d{2}))?/.exec(lowered); const h = time ? Math.min(23, Number(time[1])) : 23; const m = time ? Math.min(59, Number(time[2] ?? 0)) : 59; const iso = /(20\d{2})-(\d{2})-(\d{2})/.exec(line); const id = /\b(\d{1,2})[/-](\d{1,2})[/-](20\d{2})\b/.exec(line); const base = localBase(new Date(), timezone); if (iso) return `${iso[1]}-${iso[2]}-${iso[3]}T${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`; if (id) return `${id[3]}-${String(Number(id[2])).padStart(2, "0")}-${String(Number(id[1])).padStart(2, "0")}T${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`; if (lowered.includes("besok")) { base.setUTCDate(base.getUTCDate() + 1); return `${dateKey(base)}T${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`; } for (const [name, day] of Object.entries(weekdays)) if (lowered.includes(name)) { let distance = (day - base.getUTCDay() + 7) % 7; if (!distance) distance = 7; base.setUTCDate(base.getUTCDate() + distance); return `${dateKey(base)}T${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`; } return null; }
export function localExtraction(rawText: string, timezone: string): Result { const tasks = rawText.split(/[\n;]+/).map((x) => x.trim()).filter(Boolean).slice(0, 25).map((line): ExtractedTask => { const hours = /(\d+(?:[.,]\d+)?)\s*(?:jam|j)\b/i.exec(line); const minutes = /(\d+)\s*(?:menit|m)\b/i.exec(line); const durationMinutes = hours ? Math.round(Number(hours[1].replace(",", ".")) * 60) : minutes ? Number(minutes[1]) : 60; const lowered = line.toLowerCase(); const priority = /urgent|mendesak|segera/.test(lowered) ? "URGENT" : /prioritas tinggi|penting/.test(lowered) ? "HIGH" : /prioritas rendah|santai/.test(lowered) ? "LOW" : "MEDIUM"; const deadlineLocal = deadline(line, timezone); const splittable = /boleh dipecah|cicil|bertahap/.test(lowered); return { title: line.slice(0, 200), description: null, durationMinutes: Math.max(5, Math.min(1440, durationMinutes)), deadlineLocal, earliestStartLocal: null, priority, splittable, minimumChunkMinutes: splittable ? 30 : null, confidence: deadlineLocal ? 0.9 : hours || minutes ? 0.75 : 0.55 }; }); return extractionSchema.parse({ summary: `${tasks.length} calon tugas ditemukan.`, tasks }); }
const jsonSchema = { type: "object", properties: { summary: { type: "string" }, tasks: { type: "array", items: { type: "object", properties: { title: { type: "string" }, description: { type: ["string", "null"] }, durationMinutes: { type: "integer" }, deadlineLocal: { type: ["string", "null"] }, earliestStartLocal: { type: ["string", "null"] }, priority: { type: "string", enum: ["LOW", "MEDIUM", "HIGH", "URGENT"] }, splittable: { type: "boolean" }, minimumChunkMinutes: { type: ["integer", "null"] }, confidence: { type: "number" } }, required: ["title", "description", "durationMinutes", "deadlineLocal", "earliestStartLocal", "priority", "splittable", "minimumChunkMinutes", "confidence"], additionalProperties: false } } }, required: ["summary", "tasks"], additionalProperties: false } as const;
function outputText(data: unknown) { if (!data || typeof data !== "object") return null; const direct = (data as { output_text?: unknown }).output_text; if (typeof direct === "string") return direct; const output = (data as { output?: unknown }).output; if (!Array.isArray(output)) return null; for (const item of output) if (item && typeof item === "object" && Array.isArray((item as { content?: unknown }).content)) for (const content of (item as { content: unknown[] }).content) if (content && typeof content === "object" && (content as { type?: unknown }).type === "output_text" && typeof (content as { text?: unknown }).text === "string") return (content as { text: string }).text; return null; }
export async function extractBrainDump(rawText: string, timezone: string) { const started = Date.now(); if ((process.env.AI_PROVIDER || "mock") !== "openai") return { ...localExtraction(rawText, timezone), provider: "local", model: "deterministic-v1", latencyMs: Date.now() - started }; try { if (!process.env.AI_API_KEY) throw new Error(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 20000); const model = process.env.AI_MODEL || "gpt-5.6"; const response = await fetch(`${(process.env.AI_BASE_URL || "https://api.openai.com/v1").replace(/\/$/, "")}/responses`, { method: "POST", headers: { authorization: `Bearer ${process.env.AI_API_KEY}`, "content-type": "application/json" }, signal: controller.signal, body: JSON.stringify({ model, store: false, input: [{ role: "system", content: `Ekstrak rencana menjadi calon tugas. Zona waktu ${timezone}. Gunakan waktu lokal YYYY-MM-DDTHH:mm.` }, { role: "user", content: rawText }], text: { format: { type: "json_schema", name: "assistant_reminder_extraction", strict: true, schema: jsonSchema } } }) }); clearTimeout(timer); if (!response.ok) throw new Error(); const text = outputText(await response.json()); if (!text) throw new Error(); return { ...extractionSchema.parse(JSON.parse(text)), provider: "openai", model, latencyMs: Date.now() - started }; } catch { return { ...localExtraction(rawText, timezone), provider: "local", model: "deterministic-v1", latencyMs: Date.now() - started, warning: "AI tidak tersedia; parser lokal digunakan." }; } }
