import { NextResponse } from "next/server"; import { z } from "zod"; import { currentSession } from "@/lib/auth/session"; import { hasSafeOrigin, jsonError, readJson } from "@/lib/auth/http"; import { firstValidationMessage } from "@/lib/auth/validation"; import { prisma } from "@/lib/db/prisma"; const schema = z.object({ proposalId: z.string().uuid() });
type Snapshot = { id: string; revision: number; taskId: string | null; title: string; startsAt: string; endsAt: string; blockType: "TASK" | "ROUTINE" | "BREAK" | "PERSONAL"; flexibility: "FIXED" | "FLEXIBLE"; reminderOffsetMinutes: number | null; source: "MANUAL" | "SCHEDULER" | "RESCHEDULE" };
function snapshots(value: unknown): Snapshot[] { return Array.isArray(value) ? value.filter((item): item is Snapshot => Boolean(item && typeof item === "object" && "id" in item && "revision" in item)) : []; }
export async function POST(request: Request) {
  if (!hasSafeOrigin(request)) return jsonError("Origin permintaan tidak valid.", 403); const session = await currentSession(); if (!session) return jsonError("Silakan masuk terlebih dahulu.", 401); const parsed = schema.safeParse(await readJson(request)); if (!parsed.success) return jsonError(firstValidationMessage(parsed.error)); const proposal = await prisma.scheduleProposal.findFirst({ where: { id: parsed.data.proposalId, userId: session.userId }, include: { items: { orderBy: { startsAt: "asc" } } } }); if (!proposal || proposal.status !== "DRAFT") return jsonError("Proposal tidak tersedia.", 404); if (proposal.expiresAt <= new Date()) { await prisma.scheduleProposal.update({ where: { id: proposal.id }, data: { status: "EXPIRED" } }); return jsonError("Proposal sudah kedaluwarsa.", 409); } const old = snapshots(proposal.snapshot);
  try { const result = await prisma.$transaction(async (tx) => {
    let versionId: string | null = null;
    if (proposal.kind === "RESCHEDULE") { const current = await tx.scheduleBlock.findMany({ where: { userId: session.userId, id: { in: old.map((b) => b.id) }, status: "PLANNED" } }); if (current.length !== old.length || current.some((b) => old.find((x) => x.id === b.id)?.revision !== b.revision)) throw new Error("STALE"); const version = await tx.scheduleVersion.create({ data: { userId: session.userId, reason: "reschedule", rangeStart: proposal.rangeStart, rangeEnd: proposal.rangeEnd, items: { create: old.map((b) => ({ scheduleBlockId: b.id, snapshot: b })) } } }); versionId = version.id; await tx.notificationJob.updateMany({ where: { userId: session.userId, scheduleBlockId: { in: old.map((b) => b.id) }, status: { in: ["SCHEDULED", "PROCESSING"] } }, data: { status: "CANCELLED" } }); await tx.scheduleBlock.updateMany({ where: { userId: session.userId, id: { in: old.map((b) => b.id) } }, data: { status: "CANCELLED", revision: { increment: 1 } } }); }
    const taskIds = [...new Set(proposal.items.map((item) => item.taskId))]; const valid = await tx.task.findMany({ where: { userId: session.userId, id: { in: taskIds }, deletedAt: null, ...(proposal.kind === "NEW_SCHEDULE" ? { status: "UNSCHEDULED" as const, flexibility: "FLEXIBLE" as const } : {}) }, select: { id: true } }); if (valid.length !== taskIds.length) throw new Error("TASK");
    for (const item of proposal.items) { const block = await tx.scheduleBlock.create({ data: { userId: session.userId, taskId: item.taskId, scheduleVersionId: versionId, title: item.title, startsAt: item.startsAt, endsAt: item.endsAt, blockType: "TASK", flexibility: "FLEXIBLE", reminderOffsetMinutes: session.user.preference?.defaultReminderMinutes ?? 15, source: proposal.kind === "RESCHEDULE" ? "RESCHEDULE" : "SCHEDULER" } }); const offset = block.reminderOffsetMinutes ?? 0; if (offset > 0) await tx.notificationJob.create({ data: { userId: session.userId, scheduleBlockId: block.id, idempotencyKey: `block:${block.id}:revision:1:offset:${offset}`, scheduledFor: new Date(block.startsAt.getTime() - offset * 60000) } }); await tx.scheduleProposalItem.update({ where: { id: item.id }, data: { scheduleBlockId: block.id } }); await tx.task.update({ where: { id: item.taskId }, data: { status: "SCHEDULED" } }); }
    await tx.scheduleProposal.update({ where: { id: proposal.id }, data: { status: "CONFIRMED", confirmedAt: new Date() } }); return { blocks: proposal.items.length, versionId };
  }); return NextResponse.json({ ok: true, ...result }); } catch { return jsonError("Proposal tidak dapat disimpan karena jadwal berubah atau terjadi konflik.", 409); }
}
